// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcHl-yEe7vmQR32G_J833sNLkeZzABlBQ',
    appId: '1:12768354641:web:e0ee596be53fca276b3370',
    messagingSenderId: '12768354641',
    projectId: 'bkswp-b666d',
    authDomain: 'bkswp-b666d.firebaseapp.com',
    storageBucket: 'bkswp-b666d.appspot.com',
    measurementId: 'G-HX6FDK9539',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_03Tb0Pe1MnNoZcQx6UtWEpUIK2OEWNY',
    appId: '1:12768354641:android:6fc1c391239f68ab6b3370',
    messagingSenderId: '12768354641',
    projectId: 'bkswp-b666d',
    storageBucket: 'bkswp-b666d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAUQZHkVIt9NQWGmwBI0wZdxyEtQ_0SNI',
    appId: '1:12768354641:ios:37889521739928e06b3370',
    messagingSenderId: '12768354641',
    projectId: 'bkswp-b666d',
    storageBucket: 'bkswp-b666d.appspot.com',
    iosClientId: '12768354641-vlageeglu7onkve1hl7grku368c1fv83.apps.googleusercontent.com',
    iosBundleId: 'com.example.book',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAUQZHkVIt9NQWGmwBI0wZdxyEtQ_0SNI',
    appId: '1:12768354641:ios:37889521739928e06b3370',
    messagingSenderId: '12768354641',
    projectId: 'bkswp-b666d',
    storageBucket: 'bkswp-b666d.appspot.com',
    iosClientId: '12768354641-vlageeglu7onkve1hl7grku368c1fv83.apps.googleusercontent.com',
    iosBundleId: 'com.example.book',
  );
}
